---
calico_crd_manifest_path: "{{ calico_manifest_directory }}/projectcalico-crds.yaml"
calico_operator_manifest_path: "{{ calico_manifest_directory }}/tigera-operator.yaml"
calico_custom_resources_path: "{{ calico_manifest_directory }}/custom-resources.yaml"

calico_manifest_base_url: >-
  https://raw.githubusercontent.com/projectcalico/calico/{{
  calico_version }}/manifests
